### ISSUE TITLE
Got "invalid literal for int() with base 10" while doing bulk load on /naziscore/handlers.py:74

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/naziscore#15]
Probably not dealing with input properly

**Comment by mohit-0212** [comment]
How should i go about building your project and running it ?

**Comment by rbanffy** [comment]
You'll need a set of credentials from Twitter. You run it locally as you would run a Google app engine standard environment (https://cloud.google.com/appengine/docs/standard/python/) app, invoking dev_appserver.py. In order to make it start collecting data, you GET one of the endpoints localhost:8080/v1/twitter_id/[id]/score.json or /v1/screen_name/[name]/score.json. This issue happens only when you GET the twitter_id endpoint.

**Comment by mdaizovi** [comment]
Is this still up? If so, I'd like to take a look.

**Comment by rbanffy** [comment]
No PR for this one yet, @mdaizovi. Did you make any progress, @mohit-0212?

**Comment by mdaizovi** [comment]
I could not trigger this traceback. As far as I can tell I'm using it correctly, tried a handful of GETs on twitter_ids, both nobodies (me) and notorious nazis. Granted, this is my first time playing with Google app engine, but everything seemed to be functioning properly. Cool project.

Nonetheless, I added a try/except ValueError and if the twitter_id is not an int, result writes "twitter_id Invalid" in the browser, and logs the error. I'm interested in this project, not trying to give up, but I just couldn't reproduce this traceback.
